import type { Mentality, PlayerPosition } from './types'

export type PremierLeaguePlayerSeed = {
  name: string
  position: PlayerPosition
}

export type PremierLeagueClubSeed = {
  id: string
  name: string
  shortName: string
  city: string
  badgeUrl: string
  colors: [string, string]
  strength: number
  style: Mentality
  players: PremierLeaguePlayerSeed[]
}

export const PREMIER_LEAGUE_DATA_SNAPSHOT = '2026-08-02'

export const premierLeagueClubSeeds: PremierLeagueClubSeed[] = [
  {
    id: "arsenal",
    name: "Arsenal",
    shortName: "ARS",
    city: "Arsenal",
    badgeUrl: "https://media.api-sports.io/football/teams/42.png",
    colors: ["#db0007", "#ffffff"],
    strength: 86,
    style: "Assertive",
    players: [
      { name: "David Raya Martín", position: "GK" },
      { name: "Gabriel dos Santos Magalhães", position: "DEF" },
      { name: "Jurriën Timber", position: "DEF" },
      { name: "William Saliba", position: "DEF" },
      { name: "Riccardo Calafiori", position: "DEF" },
      { name: "Declan Rice", position: "MID" },
      { name: "Bukayo Saka", position: "MID" },
      { name: "Martín Zubimendi Ibáñez", position: "MID" },
      { name: "Eberechi Eze", position: "MID" },
      { name: "Martin Ødegaard", position: "MID" },
      { name: "Viktor Gyökeres", position: "FWD" },
      { name: "Kai Havertz", position: "FWD" },
      { name: "Piero Hincapié", position: "DEF" },
      { name: "Noni Madueke", position: "MID" },
      { name: "Mikel Merino Zazón", position: "MID" },
      { name: "Gabriel Martinelli Silva", position: "MID" },
      { name: "Benjamin White", position: "DEF" },
      { name: "Cristhian Mosquera", position: "DEF" },
    ],
  },
  {
    id: "aston-villa",
    name: "Aston Villa",
    shortName: "AVL",
    city: "Aston Villa",
    badgeUrl: "https://media.api-sports.io/football/teams/66.png",
    colors: ["#670e36", "#95bfe5"],
    strength: 79,
    style: "Measured",
    players: [
      { name: "Emiliano Martínez Romero", position: "GK" },
      { name: "Matty Cash", position: "DEF" },
      { name: "Ezri Konsa Ngoyo", position: "DEF" },
      { name: "Lucas Digne", position: "DEF" },
      { name: "Pau Torres", position: "DEF" },
      { name: "John McGinn", position: "MID" },
      { name: "Emiliano Buendía Stati", position: "MID" },
      { name: "Joao Gomes", position: "MID" },
      { name: "Amadou Onana", position: "MID" },
      { name: "Boubacar Kamara", position: "MID" },
      { name: "Ollie Watkins", position: "FWD" },
      { name: "Tammy Abraham", position: "FWD" },
      { name: "Alejandro Garnacho Ferreyra", position: "MID" },
      { name: "Ross Barkley", position: "MID" },
      { name: "Ian Maatsen", position: "DEF" },
      { name: "Tyrone Mings", position: "DEF" },
      { name: "Evann Guessand", position: "MID" },
      { name: "Lamare Bogarde", position: "MID" },
    ],
  },
  {
    id: "bournemouth",
    name: "Bournemouth",
    shortName: "BOU",
    city: "Bournemouth",
    badgeUrl: "https://media.api-sports.io/football/teams/35.png",
    colors: ["#da291c", "#000000"],
    strength: 73,
    style: "Assertive",
    players: [
      { name: "Đorđe Petrović", position: "GK" },
      { name: "Adrien Truffert", position: "DEF" },
      { name: "James Hill", position: "DEF" },
      { name: "Adam Smith", position: "DEF" },
      { name: "Bafodé Diakité", position: "DEF" },
      { name: "Marcus Tavernier", position: "MID" },
      { name: "Alex Scott", position: "MID" },
      { name: "Junior Kroupi", position: "MID" },
      { name: "Tyler Adams", position: "MID" },
      { name: "Rayan Vitor Simplício Rocha", position: "MID" },
      { name: "Francisco Evanilson de Lima Barbosa", position: "FWD" },
      { name: "Enes Ünal", position: "FWD" },
      { name: "Amine Adli", position: "MID" },
      { name: "David Brooks", position: "MID" },
      { name: "Ryan Christie", position: "MID" },
      { name: "Justin Kluivert", position: "MID" },
      { name: "Lewis Cook", position: "MID" },
      { name: "Veljko Milosavljevic", position: "DEF" },
    ],
  },
  {
    id: "brentford",
    name: "Brentford",
    shortName: "BRE",
    city: "Brentford",
    badgeUrl: "https://media.api-sports.io/football/teams/55.png",
    colors: ["#e30613", "#fdb913"],
    strength: 75,
    style: "Relentless",
    players: [
      { name: "Caoimhín Kelleher", position: "GK" },
      { name: "Nathan Collins", position: "DEF" },
      { name: "Michael Kayode", position: "DEF" },
      { name: "Sepp van den Berg", position: "DEF" },
      { name: "Kristoffer Ajer", position: "DEF" },
      { name: "Dango Ouattara", position: "MID" },
      { name: "Kevin Schade", position: "MID" },
      { name: "Keane Lewis-Potter", position: "MID" },
      { name: "Mikkel Damsgaard", position: "MID" },
      { name: "Yehor Yarmoliuk", position: "MID" },
      { name: "Igor Thiago Nascimento Rodrigues", position: "FWD" },
      { name: "Kaye Furo", position: "FWD" },
      { name: "Mathias Jensen", position: "MID" },
      { name: "Vitaly Janelt", position: "MID" },
      { name: "Rico Henry", position: "DEF" },
      { name: "Aaron Hickey", position: "DEF" },
      { name: "Ethan Pinnock", position: "DEF" },
      { name: "Fábio Freitas Gouveia Carvalho", position: "MID" },
    ],
  },
  {
    id: "brighton",
    name: "Brighton & Hove Albion",
    shortName: "BHA",
    city: "Brighton",
    badgeUrl: "https://media.api-sports.io/football/teams/51.png",
    colors: ["#0057b8", "#ffffff"],
    strength: 76,
    style: "Measured",
    players: [
      { name: "Bart Verbruggen", position: "GK" },
      { name: "Ferdi Kadıoğlu", position: "DEF" },
      { name: "Pascal Struijk", position: "DEF" },
      { name: "Lewis Dunk", position: "DEF" },
      { name: "Mats Wieffer", position: "DEF" },
      { name: "Yankuba Minteh", position: "MID" },
      { name: "Yasin Ayari", position: "MID" },
      { name: "Diego Gómez Amarilla", position: "MID" },
      { name: "Jack Hinshelwood", position: "MID" },
      { name: "Pascal Groß", position: "MID" },
      { name: "Danny Welbeck", position: "FWD" },
      { name: "Georginio Rutter", position: "FWD" },
      { name: "Maxim De Cuyper", position: "DEF" },
      { name: "Mitoma Kaoru", position: "MID" },
      { name: "Carlos Baleba", position: "MID" },
      { name: "Olivier Boscagli", position: "DEF" },
      { name: "Charalampos Kostoulas", position: "FWD" },
      { name: "Matt O'Riley", position: "MID" },
    ],
  },
  {
    id: "chelsea",
    name: "Chelsea",
    shortName: "CHE",
    city: "Chelsea",
    badgeUrl: "https://media.api-sports.io/football/teams/49.png",
    colors: ["#034694", "#dba111"],
    strength: 83,
    style: "Assertive",
    players: [
      { name: "Robert Lynch Sánchez", position: "GK" },
      { name: "Maxence Lacroix", position: "DEF" },
      { name: "Trevoh Chalobah", position: "DEF" },
      { name: "Reece James", position: "DEF" },
      { name: "Malo Gusto", position: "DEF" },
      { name: "Morgan Rogers", position: "MID" },
      { name: "Enzo Fernández", position: "MID" },
      { name: "Pedro Lomba Neto", position: "MID" },
      { name: "Cole Palmer", position: "MID" },
      { name: "Moisés Caicedo Corozo", position: "MID" },
      { name: "João Pedro Junqueira de Jesus", position: "FWD" },
      { name: "Liam Delap", position: "FWD" },
      { name: "Wesley Fofana", position: "DEF" },
      { name: "Estêvão Almeida de Oliveira Gonçalves", position: "MID" },
      { name: "Josh Acheampong", position: "DEF" },
      { name: "Tosin Adarabioyo", position: "DEF" },
      { name: "Jamie Bynoe-Gittens", position: "MID" },
      { name: "Jorrel Hato", position: "DEF" },
    ],
  },
  {
    id: "coventry",
    name: "Coventry City",
    shortName: "COV",
    city: "Coventry",
    badgeUrl: "https://media.api-sports.io/football/teams/134.png",
    colors: ["#1d428a", "#ffffff"],
    strength: 70,
    style: "Measured",
    players: [
      { name: "Ben Wilson", position: "GK" },
      { name: "Bobby Thomas", position: "DEF" },
      { name: "Liam Kitching", position: "DEF" },
      { name: "Milan van Ewijk", position: "DEF" },
      { name: "Jay Dasilva", position: "DEF" },
      { name: "Frank Onyeka", position: "MID" },
      { name: "Ephron Mason-Clark", position: "MID" },
      { name: "Victor Torp", position: "MID" },
      { name: "Loum Tchaouna", position: "MID" },
      { name: "Jack Rudoni", position: "MID" },
      { name: "Haji Wright", position: "FWD" },
      { name: "Brandon Thomas-Asante", position: "FWD" },
      { name: "Matt Grimes", position: "MID" },
      { name: "Tatsuhiro Sakamoto", position: "MID" },
      { name: "Josh Eccles", position: "MID" },
      { name: "Ellis Simms", position: "FWD" },
      { name: "Jahnoah Markelo", position: "FWD" },
      { name: "George Shepherd", position: "MID" },
    ],
  },
  {
    id: "crystal-palace",
    name: "Crystal Palace",
    shortName: "CRY",
    city: "Crystal Palace",
    badgeUrl: "https://media.api-sports.io/football/teams/52.png",
    colors: ["#1b458f", "#c4122e"],
    strength: 75,
    style: "Relentless",
    players: [
      { name: "Dean Henderson", position: "GK" },
      { name: "Daniel Muñoz Mejía", position: "DEF" },
      { name: "Tyrick Mitchell", position: "DEF" },
      { name: "Chris Richards", position: "DEF" },
      { name: "Jaydee Canvot", position: "DEF" },
      { name: "Ismaïla Sarr", position: "MID" },
      { name: "Adam Wharton", position: "MID" },
      { name: "Yéremy Pino Santos", position: "MID" },
      { name: "Jefferson Lerma Solís", position: "MID" },
      { name: "Daichi Kamada", position: "MID" },
      { name: "Jean-Philippe Mateta", position: "FWD" },
      { name: "Jørgen Strand Larsen", position: "FWD" },
      { name: "Brennan Johnson", position: "MID" },
      { name: "Will Hughes", position: "MID" },
      { name: "Justin Devenny", position: "MID" },
      { name: "Eddie Nketiah", position: "FWD" },
      { name: "Chadi Riad Dnanou", position: "DEF" },
      { name: "Walter Benítez", position: "GK" },
    ],
  },
  {
    id: "everton",
    name: "Everton",
    shortName: "EVE",
    city: "Everton",
    badgeUrl: "https://media.api-sports.io/football/teams/45.png",
    colors: ["#003399", "#ffffff"],
    strength: 73,
    style: "Assertive",
    players: [
      { name: "Jordan Pickford", position: "GK" },
      { name: "James Tarkowski", position: "DEF" },
      { name: "Michael Keane", position: "DEF" },
      { name: "Jake O'Brien", position: "DEF" },
      { name: "Vitalii Mykolenko", position: "DEF" },
      { name: "James Garner", position: "MID" },
      { name: "Kiernan Dewsbury-Hall", position: "MID" },
      { name: "Iliman Ndiaye", position: "MID" },
      { name: "Tim Iroegbunam", position: "MID" },
      { name: "Dwight McNeil", position: "MID" },
      { name: "Norberto Bercique Gomes Betuncal", position: "FWD" },
      { name: "Thierno Barry", position: "FWD" },
      { name: "Merlin Röhl", position: "MID" },
      { name: "Jarrad Branthwaite", position: "DEF" },
      { name: "Carlos Alcaraz Durán", position: "MID" },
      { name: "Nathan Patterson", position: "DEF" },
      { name: "Harrison Armstrong", position: "MID" },
      { name: "Tyler Dibling", position: "MID" },
    ],
  },
  {
    id: "fulham",
    name: "Fulham",
    shortName: "FUL",
    city: "Fulham",
    badgeUrl: "https://media.api-sports.io/football/teams/36.png",
    colors: ["#000000", "#ffffff"],
    strength: 72,
    style: "Measured",
    players: [
      { name: "Bernd Leno", position: "GK" },
      { name: "Joachim Andersen", position: "DEF" },
      { name: "Calvin Bassey", position: "DEF" },
      { name: "Ryan Sessegnon", position: "DEF" },
      { name: "Kenny Tete", position: "DEF" },
      { name: "Alex Iwobi", position: "MID" },
      { name: "Sander Berge", position: "MID" },
      { name: "Emile Smith Rowe", position: "MID" },
      { name: "Saša Lukić", position: "MID" },
      { name: "Josh King", position: "MID" },
      { name: "Rodrigo Muniz Carvalho", position: "FWD" },
      { name: "Jonah Kusi-Asare", position: "FWD" },
      { name: "Antonee Robinson", position: "DEF" },
      { name: "Timothy Castagne", position: "DEF" },
      { name: "Kevin Santos Lopes de Macedo", position: "MID" },
      { name: "Oscar Bobb", position: "MID" },
      { name: "Tom Cairney", position: "MID" },
      { name: "Jorge Cuenca Barreno", position: "DEF" },
    ],
  },
  {
    id: "hull-city",
    name: "Hull City",
    shortName: "HUL",
    city: "Hull",
    badgeUrl: "https://media.api-sports.io/football/teams/322.png",
    colors: ["#f5a800", "#000000"],
    strength: 69,
    style: "Assertive",
    players: [
      { name: "Jack Butland", position: "GK" },
      { name: "John Egan", position: "DEF" },
      { name: "Charlie Hughes", position: "DEF" },
      { name: "Semi Ajayi", position: "DEF" },
      { name: "Lewie Coyle", position: "DEF" },
      { name: "Mohamed Belloumi", position: "MID" },
      { name: "Liam Millar", position: "MID" },
      { name: "Abdülkadir Ömür", position: "MID" },
      { name: "Abu Kamara", position: "MID" },
      { name: "David Akintola", position: "MID" },
      { name: "Oli McBurnie", position: "FWD" },
      { name: "Enis Destan", position: "FWD" },
      { name: "Hidemasa Morita", position: "MID" },
      { name: "Kieran Dowell", position: "MID" },
      { name: "Matt Crooks", position: "MID" },
      { name: "Regan Slater", position: "MID" },
      { name: "Eliot Matazo", position: "MID" },
      { name: "Óscar Zambrano", position: "MID" },
    ],
  },
  {
    id: "ipswich-town",
    name: "Ipswich Town",
    shortName: "IPS",
    city: "Ipswich",
    badgeUrl: "https://media.api-sports.io/football/teams/57.png",
    colors: ["#3b5da8", "#ffffff"],
    strength: 68,
    style: "Relentless",
    players: [
      { name: "Christian Walton", position: "GK" },
      { name: "Issa Diop", position: "DEF" },
      { name: "Cédric Kipré", position: "DEF" },
      { name: "Dara O'Shea", position: "DEF" },
      { name: "Leif Davis", position: "DEF" },
      { name: "Jack Clarke", position: "MID" },
      { name: "Abdul Fatawu", position: "MID" },
      { name: "Jaden Philogene", position: "MID" },
      { name: "Daizen Maeda", position: "MID" },
      { name: "Marcelino Núñez", position: "MID" },
      { name: "Emersonn Correia da Silva", position: "FWD" },
      { name: "George Hirst", position: "FWD" },
      { name: "Azor Matusiwa", position: "MID" },
      { name: "Wes Burns", position: "MID" },
      { name: "Chiedozie Ogbene", position: "MID" },
      { name: "Sam Szmodics", position: "MID" },
      { name: "Chuba Akpom", position: "FWD" },
      { name: "Ali Al-Hamadi", position: "FWD" },
    ],
  },
  {
    id: "leeds",
    name: "Leeds United",
    shortName: "LEE",
    city: "Leeds",
    badgeUrl: "https://media.api-sports.io/football/teams/63.png",
    colors: ["#ffcd00", "#1d428a"],
    strength: 75,
    style: "Relentless",
    players: [
      { name: "Lucas Estella Perri", position: "GK" },
      { name: "Joe Rodon", position: "DEF" },
      { name: "Jaka Bijol", position: "DEF" },
      { name: "Jayden Bogle", position: "DEF" },
      { name: "James Justin", position: "DEF" },
      { name: "Harry Wilson", position: "MID" },
      { name: "Anton Stach", position: "MID" },
      { name: "Ethan Ampadu", position: "MID" },
      { name: "Brenden Aaronson", position: "MID" },
      { name: "Noah Okafor", position: "MID" },
      { name: "Dominic Calvert-Lewin", position: "FWD" },
      { name: "Lukas Nmecha", position: "FWD" },
      { name: "Gabriel Gudmundsson", position: "DEF" },
      { name: "Tanaka Ao", position: "MID" },
      { name: "Ilia Gruev", position: "MID" },
      { name: "Sean Longstaff", position: "MID" },
      { name: "Wilfried Gnonto", position: "MID" },
      { name: "Sebastiaan Bornauw", position: "DEF" },
    ],
  },
  {
    id: "liverpool",
    name: "Liverpool",
    shortName: "LIV",
    city: "Liverpool",
    badgeUrl: "https://media.api-sports.io/football/teams/40.png",
    colors: ["#c8102e", "#00b2a9"],
    strength: 87,
    style: "Relentless",
    players: [
      { name: "Alisson Becker", position: "GK" },
      { name: "Virgil van Dijk", position: "DEF" },
      { name: "Milos Kerkez", position: "DEF" },
      { name: "Jeremie Frimpong", position: "DEF" },
      { name: "Conor Bradley", position: "DEF" },
      { name: "Dominik Szoboszlai", position: "MID" },
      { name: "Ryan Gravenberch", position: "MID" },
      { name: "Cody Gakpo", position: "MID" },
      { name: "Florian Wirtz", position: "MID" },
      { name: "Alexis Mac Allister", position: "MID" },
      { name: "Hugo Ekitiké", position: "FWD" },
      { name: "Alexander Isak", position: "FWD" },
      { name: "Curtis Jones", position: "MID" },
      { name: "Rio Ngumoha", position: "MID" },
      { name: "Federico Chiesa", position: "MID" },
      { name: "Giorgi Mamardashvili", position: "GK" },
      { name: "Joe Gomez", position: "DEF" },
      { name: "Endo Wataru", position: "MID" },
    ],
  },
  {
    id: "manchester-city",
    name: "Manchester City",
    shortName: "MCI",
    city: "Manchester",
    badgeUrl: "https://media.api-sports.io/football/teams/50.png",
    colors: ["#6cabdd", "#ffffff"],
    strength: 90,
    style: "Measured",
    players: [
      { name: "Gianluigi Donnarumma", position: "GK" },
      { name: "Marc Guéhi", position: "DEF" },
      { name: "Nico O'Reilly", position: "DEF" },
      { name: "Matheus Nunes", position: "DEF" },
      { name: "Rúben dos Santos Gato Alves Dias", position: "DEF" },
      { name: "Antoine Semenyo", position: "MID" },
      { name: "Elliot Anderson", position: "MID" },
      { name: "Rayan Cherki", position: "MID" },
      { name: "Phil Foden", position: "MID" },
      { name: "Jérémy Doku", position: "MID" },
      { name: "Erling Haaland", position: "FWD" },
      { name: "Omar Marmoush", position: "FWD" },
      { name: "Tijjani Reijnders", position: "MID" },
      { name: "Jack Grealish", position: "MID" },
      { name: "Joško Gvardiol", position: "DEF" },
      { name: "Rodrigo 'Rodri' Hernandez Cascante", position: "MID" },
      { name: "Abdukodir Khusanov", position: "DEF" },
      { name: "Nico González Iglesias", position: "MID" },
    ],
  },
  {
    id: "manchester-united",
    name: "Manchester United",
    shortName: "MUN",
    city: "Manchester",
    badgeUrl: "https://media.api-sports.io/football/teams/33.png",
    colors: ["#da291c", "#fbe122"],
    strength: 82,
    style: "Assertive",
    players: [
      { name: "Senne Lammens", position: "GK" },
      { name: "Luke Shaw", position: "DEF" },
      { name: "Diogo Dalot Teixeira", position: "DEF" },
      { name: "Harry Maguire", position: "DEF" },
      { name: "Leny Yoro", position: "DEF" },
      { name: "Bruno Borges Fernandes", position: "MID" },
      { name: "Bryan Mbeumo", position: "MID" },
      { name: "Matheus Santos Carneiro da Cunha", position: "MID" },
      { name: "Patrick Dorgu", position: "MID" },
      { name: "Amad Diallo", position: "MID" },
      { name: "Benjamin Sesko", position: "FWD" },
      { name: "Joshua Zirkzee", position: "FWD" },
      { name: "Kobbie Mainoo", position: "MID" },
      { name: "Karl Darlow", position: "GK" },
      { name: "Youri Tielemans", position: "MID" },
      { name: "Mason Mount", position: "MID" },
      { name: "Noussair Mazraoui", position: "DEF" },
      { name: "Lisandro Martínez", position: "DEF" },
    ],
  },
  {
    id: "newcastle",
    name: "Newcastle United",
    shortName: "NEW",
    city: "Newcastle",
    badgeUrl: "https://media.api-sports.io/football/teams/34.png",
    colors: ["#241f20", "#ffffff"],
    strength: 80,
    style: "Relentless",
    players: [
      { name: "Nick Pope", position: "GK" },
      { name: "Malick Thiaw", position: "DEF" },
      { name: "Dan Burn", position: "DEF" },
      { name: "Sven Botman", position: "DEF" },
      { name: "Lewis Hall", position: "DEF" },
      { name: "Bruno Guimarães Rodriguez Moura", position: "MID" },
      { name: "Harvey Barnes", position: "MID" },
      { name: "Jacob Murphy", position: "MID" },
      { name: "Joelinton Cássio Apolinário de Lira", position: "MID" },
      { name: "Lewis Miley", position: "MID" },
      { name: "Nick Woltemade", position: "FWD" },
      { name: "William Osula", position: "FWD" },
      { name: "Jacob Ramsey", position: "MID" },
      { name: "Tino Livramento", position: "DEF" },
      { name: "Fabian Schär", position: "DEF" },
      { name: "Anthony Elanga", position: "MID" },
      { name: "Joe Willock", position: "MID" },
      { name: "Yoane Wissa", position: "FWD" },
    ],
  },
  {
    id: "nottingham-forest",
    name: "Nottingham Forest",
    shortName: "NFO",
    city: "Nottingham Forest",
    badgeUrl: "https://media.api-sports.io/football/teams/65.png",
    colors: ["#e53233", "#ffffff"],
    strength: 77,
    style: "Measured",
    players: [
      { name: "Matz Sels", position: "GK" },
      { name: "Neco Williams", position: "DEF" },
      { name: "Nikola Milenković", position: "DEF" },
      { name: "Murillo Costa dos Santos", position: "DEF" },
      { name: "Ola Aina", position: "DEF" },
      { name: "Morgan Gibbs-White", position: "MID" },
      { name: "Ibrahim Sangaré", position: "MID" },
      { name: "Callum Hudson-Odoi", position: "MID" },
      { name: "Omari Hutchinson", position: "MID" },
      { name: "Dan Ndoye", position: "MID" },
      { name: "Igor Jesus Maciel da Cruz", position: "FWD" },
      { name: "Taiwo Awoniyi", position: "FWD" },
      { name: "Felipe Rodrigues da Silva", position: "DEF" },
      { name: "Nicolás Domínguez", position: "MID" },
      { name: "Chris Wood", position: "FWD" },
      { name: "Nicolò Savona", position: "DEF" },
      { name: "Ryan Yates", position: "MID" },
      { name: "Dilane Bakwa", position: "MID" },
    ],
  },
  {
    id: "tottenham-hotspur",
    name: "Tottenham Hotspur",
    shortName: "TOT",
    city: "Tottenham Hotspur",
    badgeUrl: "https://media.api-sports.io/football/teams/746.png",
    colors: ["#132257", "#ffffff"],
    strength: 79,
    style: "Assertive",
    players: [
      { name: "Martin Dubravka", position: "GK" },
      { name: "Marcos Senesi Barón", position: "DEF" },
      { name: "Jan Paul van Hecke", position: "DEF" },
      { name: "Pedro Porro Sauceda", position: "DEF" },
      { name: "Micky van de Ven", position: "DEF" },
      { name: "Mateus Fernandes", position: "MID" },
      { name: "Rodrigo Bentancur", position: "MID" },
      { name: "Sandro Tonali", position: "MID" },
      { name: "Xavi Simons", position: "MID" },
      { name: "Mathys Tel", position: "MID" },
      { name: "Richarlison de Andrade", position: "FWD" },
      { name: "Dominic Solanke-Mitchell", position: "FWD" },
      { name: "Cristian Romero", position: "DEF" },
      { name: "Guglielmo Vicario", position: "GK" },
      { name: "Djed Spence", position: "DEF" },
      { name: "Mohammed Kudus", position: "MID" },
      { name: "Pape Matar Sarr", position: "MID" },
      { name: "Kevin Danso", position: "DEF" },
    ],
  },
  {
    id: "sunderland",
    name: "Sunderland",
    shortName: "SUN",
    city: "Sunderland",
    badgeUrl: "https://media.api-sports.io/football/teams/47.png",
    colors: ["#eb172b", "#ffffff"],
    strength: 69,
    style: "Assertive",
    players: [
      { name: "Robin Roefs", position: "GK" },
      { name: "Nordi Mukiele", position: "DEF" },
      { name: "Omar Alderete", position: "DEF" },
      { name: "Daniel Ballard", position: "DEF" },
      { name: "Trai Hume", position: "DEF" },
      { name: "Enzo Le Fée", position: "MID" },
      { name: "Granit Xhaka", position: "MID" },
      { name: "Chemsdine Talbi", position: "MID" },
      { name: "Noah Sadiki", position: "MID" },
      { name: "Habib Diarra", position: "MID" },
      { name: "Brian Brobbey", position: "FWD" },
      { name: "Wilson Isidor", position: "FWD" },
      { name: "Reinildo Mandava", position: "DEF" },
      { name: "Chris Rigg", position: "MID" },
      { name: "Simon Adingra", position: "MID" },
      { name: "Luke O'Nien", position: "DEF" },
      { name: "Melker Ellborg", position: "GK" },
      { name: "Romaine Mundle", position: "MID" },
    ],
  },
]
